FROM workflow-server:local
COPY --chown=65532:65532 scenarios/63-twilio-integration/plugins/workflow-plugin-twilio/workflow-plugin-twilio-linux /data/plugins/workflow-plugin-twilio/workflow-plugin-twilio
COPY --chown=65532:65532 scenarios/63-twilio-integration/plugins/workflow-plugin-twilio/plugin.json /data/plugins/workflow-plugin-twilio/plugin.json
