apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scenario-10-data
  namespace: wf-scenario-10
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: workflow-server
    scenario: "10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
