apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scenario-13-data
  namespace: wf-scenario-13
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: workflow-server
    scenario: "13"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
