apiVersion: v1
kind: Service
metadata:
  name: workflow-server
  namespace: wf-scenario-07
spec:
  selector:
    app: workflow-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: admin
      port: 8081
      targetPort: 8081
