apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scenario-21-data
  namespace: wf-scenario-21
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: workflow-server
    scenario: "21"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
