apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scenario-14-data
  namespace: wf-scenario-14
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app: workflow-server
    scenario: "14"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
